#!/usr/bin/env bash
# A script that configures an nginx server to return a string
# The content of the string must be 'Hello World!'

# Update package list and install nginx
apt-get update
apt-get install nginx -y

# Modify nginx default site configuration
var='/etc/nginx/sites-available/default'

# Change the root directory and ensure index.html is served
sed -i 's|root /var/www/html;|root /var/www/html;|' "$var"
sed -i 's|index.nginx-debian.html|index.html|' "$var"

# Create an index.html file with 'Hello World!' string
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx to apply the changes
/etc/init.d/nginx restart
