#!/usr/bin/env bash
#Serve a page with Nginx: configure Nginx to serve your page from the route /airbnb-onepage/
server {
    # Listen's on port 80
    listen      80 default_server;
    listen      [::]:80 default_server ipv6only=on;


    #ip address of your domain name/server
    server_name  34.207.120.10;


    #custom header name
    add_header  X-Served-By $HOSTNAME;


    # serve /airbnb-onepage/ route from AirBnb_clone_v2
    location = /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000/airbnb-onepage/;
    }

    # 404 error handling page
    error_page 400 /404.html;
    location /404 {
        root /var/www/html;
        internal;
    }
}
